import { Router } from 'express';
import { UserController } from "../controllers/userAPI";
import { validateAuthHeader, addWhitelistStatus, validateWhitelistOnLogin } from "../helpers/middleware";

const userRouter: Router = Router();
const userController: UserController = new UserController();

userRouter.post("/validateUserToken", validateAuthHeader, addWhitelistStatus, userController.validateUserToken);
userRouter.post("/checkemail", userController.checkEmail);
userRouter.get("/checkWhitelist/:email", userController.checkWhitelistStatus);
userRouter.post("/checkByemail", userController.checkByEmail);
userRouter.post("/checkByphone", userController.checkByPhone);
userRouter.post("/checkByWebWalletEmail", userController.checkByWalletEmail);
userRouter.post("/checkusername", userController.checkUsername);
userRouter.post("/register", userController.registerUser);
userRouter.post("/registerwithapp", userController.registerUserWithApp);
userRouter.post("/registerwithapptest", userController.registerUserWithAppTest);
userRouter.post("/registertest", userController.registerUser0);
userRouter.post("/register/apple", userController.registerUserWithApple);
userRouter.post("/register/google", userController.registerUserWithGoogle);
userRouter.post("/login/google", validateWhitelistOnLogin, userController.loginUserWithGoogle);
userRouter.post("/login/apple", validateWhitelistOnLogin, userController.loginUserWithApple);
userRouter.post("/login", validateWhitelistOnLogin, userController.issueToken);
userRouter.post("/loginWithOtp", validateWhitelistOnLogin, userController.loginWithOtp);
userRouter.post("/loginWithToken", validateWhitelistOnLogin, userController.issueTokenWithSignInToken);
userRouter.post("/hivelogin", validateWhitelistOnLogin, userController.issueTokenHive);
userRouter.post("/refreshToken", userController.refreshToken);
userRouter.post("/logout", validateAuthHeader, userController.logout);
userRouter.post("/validateEmail", userController.validateEmail);
userRouter.post("/validateOtp", userController.validateEmailOtp);
userRouter.post("/validateForgotOtp", userController.validateForgotEmailOtp);
userRouter.post("/sendOtp", userController.sendOtpToEmail);
userRouter.post("/sendForgotOtp", userController.sendForgotOtpToEmail);
userRouter.post("/forgotPassword", userController.forgotPassword);
userRouter.post("/resetPassword", userController.resetPassword);
userRouter.post("/resetPasswordWithPhone", userController.resetPasswordWithPhone);
userRouter.post("/changePassword", userController.changePassword);
userRouter.post("/resendEmailCode", userController.resendEmailCode);
userRouter.post("/setPassword", validateAuthHeader, userController.setPassword);
userRouter.post("/getUserDetails/:email", addWhitelistStatus, userController.getUserDetails);
userRouter.post("/getAllUserDetails/:email", addWhitelistStatus, userController.getAllUserDetails);
userRouter.get("/getAllUserDetailsForAdmin/:email", addWhitelistStatus, userController.getAllUserDetailsForAdmin);
userRouter.get("/getHoneyUserDetails/:email", addWhitelistStatus, userController.getHoneybeeUserDetails);
userRouter.post("/getUserLiteDetails/:email", addWhitelistStatus, userController.getUserLiteDetails);
userRouter.get("/getMiningLiteDetails/:email", addWhitelistStatus, userController.getMiningLiteDetails);
userRouter.get("/getAllUsersLite", addWhitelistStatus, userController.getUsersLite);
userRouter.get("/getHiveUsersLite", addWhitelistStatus, userController.getHiveUsersLite);
userRouter.post("/getUsers", addWhitelistStatus, userController.getUsers);
userRouter.get("/getUserCount", userController.getUsersCount);
userRouter.post("/getUserOrders/:email", userController.getUserOrders);
userRouter.get("/getUserCompletedOrders/:email", userController.getUserCompletedOrders);
userRouter.get("/getUserOrder/:email/:orderId", userController.getUserOrder);
userRouter.get("/getUserMiningSubscriptionOrders/:email", userController.getUserMiningSubscriptionOrders);
userRouter.get("/getUserRewardDetails/:email", userController.getUserRewardDetails);
userRouter.post("/getUserWallets/:email", userController.getUserWallets);
userRouter.post("/getUserDemoWallets/:email", userController.getDemoUserWallets);
userRouter.get("/getUserWallets/:email", userController.getUserWallets);
userRouter.get("/getUserWallets/:email", userController.getUserWallets);
userRouter.get("/getUserWallet/:email/:coin/:network", userController.getUserWalletbyNetwork);
userRouter.get("/getBTCYAcknowledgementStatus/:email", userController.getAcknowledgementStatus);
userRouter.get("/updateBTCYAcknowledgementStatus", userController.updateBtcyAcknowledgementStatus);
userRouter.get("/getBTCYMigrationStatus/:email", userController.getBTCYMigrationStatus);
userRouter.post("/updateBTCYMigrationStatus", userController.updateBTCYMigrationStatus);
userRouter.post("/withdrawBTCY", userController.withdrawBTCY);
userRouter.post("/createUserWallet", userController.createUserWalletbyNetwork);
userRouter.get("/getPrivacySettings/:email", userController.getPrivacySettings);
userRouter.post("/updateBTCYPrivacySettings", userController.updateBTCYPrivacySettings);
userRouter.get("/totalInvestment/:email", userController.totalInvestmentForEmail);
userRouter.get("/totalDemoInvestment/:email", userController.totalDemoInvestmentForEmail);
userRouter.post("/getTransactions/:email", userController.getTransactions);
userRouter.post("/verifyPhone", userController.verifyPhone);
userRouter.post("/addPhone", userController.addPhone);
userRouter.post("/addRewards", userController.addRewards);
userRouter.post("/updateRewards", userController.updateRewards);
userRouter.post("/updateRewardsWallet", userController.updateRewardWalletAddress);
userRouter.post("/fundWallet", userController.fundWallet); // Fund wallet with test currency
userRouter.post("/getBalance/:email/:coin", userController.getBalance);
userRouter.post("/getBalance/:email/:coin/:network", userController.getBalanceByNetwork);
userRouter.post("/btcy/yingyang/debit", userController.debitBtcyYingYangBalance);
userRouter.get("/wallstreet/usd-balance", userController.getWallstreetUsdBalance);
userRouter.post("/wallstreet/usd-balance/update", userController.updateWallstreetUsdBalance);
userRouter.post("/withdrawRewards", userController.withdrawRewards);
userRouter.post("/updateFavCurrencies", userController.updateFavCurrencies);
userRouter.post("/createBug", userController.createBug);
userRouter.get("/getUserCreatedBugs/:email", userController.getBugs);
userRouter.get("/getBug/:bugId", userController.getBug);
userRouter.post("/updateBug", userController.updateBug);
userRouter.post("/uploadBugFile", userController.uploadBugFile);
userRouter.get("/getTaskCenterDetails/:email", userController.getTaskCenterDetails);
userRouter.post("/enableTradeToEarn", userController.enableTradeToEarn);
userRouter.get("/getPaypalOrder/:token", userController.getPaypalOrder);
userRouter.get("/referrals/:email", userController.getReferralsByEmail);
userRouter.get("/validatereferralcode/:referralCode", userController.validatedReferralCode);
userRouter.get("/getPaypalSubscription/:subscriptionId", userController.getPaypalSubscription);
userRouter.get("/getpermissions/:email", userController.getPermissionsForCaptains);
userRouter.post("/updatepermissions", userController.updatePermissionsForCaptains);
userRouter.post("/profile/save", validateAuthHeader, addWhitelistStatus, userController.saveUserProfile);
userRouter.post("/updateprofile", addWhitelistStatus, userController.updateUserProfile);
userRouter.get("/getProfileDetails/:email", addWhitelistStatus, userController.getUserProfile);
userRouter.post("/updateLanguage", userController.updateUserLanguage);
userRouter.post("/addphone", userController.addPhoneNumber);
userRouter.post("/reportcompromised", userController.reportCompromisedAccount);
userRouter.post("/reportfake", userController.reportFakeAccount);
userRouter.post("/deleteaccount", validateAuthHeader, userController.deleteAccount);
userRouter.get("/deleteaccount/:email", userController.deleteAccountWithEmail);
userRouter.get("/getReferredUserDetails/:email", userController.getReferredUserDetails);
userRouter.get('/getHoneyUserDashbaord/:username', userController.getAllHoneyBeeDashboardData);
userRouter.post('/requestpermssions', userController.requestPermissionsByCaptain);
userRouter.post("/updatepowerpack", userController.updatePowerPackDetail);
userRouter.post("/postpublicMessage", userController.postPublicMessages);
userRouter.get("/getpublicMessages/:email", userController.getPublicMessages);
userRouter.get("/getpublicMessagesByName/:name", userController.getPublicMessagesByUsername);
userRouter.post("/stakecoin", userController.stakeCryptoCoin);
userRouter.post("/smartApy", userController.smartApyInvest);
userRouter.post("/withdrawSmartApy", userController.runWithdrawSmartAPYForSpecificUser);
userRouter.post("/reinvestSmartApy", userController.reinvestUserSmartApy);
userRouter.post("/calculateStake", userController.calculateStakeReward);
userRouter.get("/getStakedCoins/:email", userController.getstakedCryptoCoin);
userRouter.get("/getSmartApyInvestmens/:email", userController.getSmartAPYInvestments);
userRouter.get("/getCommissionHistory/:email", userController.getCommissionHistory);
userRouter.get("/getUserByUsername/:username", userController.getUserByUsername);
userRouter.get("/getUserByEmail/:email", userController.getUserByEmail);
// User participates in a lottery
userRouter.post("/participateInLottery", userController.participateInLottery);
userRouter.get("/participatedLottery/:email", userController.participatedLotteries);
// Route to add lottery tickets to a cart
userRouter.post("/lottery/tickets/addToCart", userController.addLotteryTicketsToCart);
// Route to get lottery tickets in a cart, 
userRouter.get("/lottery/tickets/getInCart", userController.getLotteryTicketsInCart);
userRouter.get("/lottery/tickets/getInCartByEmail", userController.getLotteryTicketsInCartByEmail);
// Route to update lottery tickets in a cart
//("banks144@yahoo.com", "donpanchos4me@gmail.com", "rey.barthelemy@gmail.com", "fowlertrucking14@yahoo.com", "cielinoinc@gmail.com", "lynn@indexx.ai", "martinmonge@verizon.net", "kathy.oglesbee@yahoo.com").
userRouter.put("/lottery/tickets/updateInCart", userController.updateLotteryTicketsInCart);
userRouter.post("/claimtoken", userController.claimFreeTokens);
userRouter.get("/getclaimtoken/:email", userController.getClaimFreeTokens);
userRouter.post("/groupRewards", userController.getClaimFreeTokens);
userRouter.get("/createShortToken/:email", userController.getShortToken);
userRouter.post("/academy/updateToken", userController.addRewardsForCoursePurchase);
userRouter.get("/getAllRefferedUsers/:email", userController.getAllRefferedUsers);
userRouter.post("/validateVoucher", userController.validateGiftCard);
userRouter.post("/redeemCoupon", userController.redeemGiftCard);
userRouter.post("/createGiftcard", userController.createGiftCard);
userRouter.post("/sendGiftcard", userController.sendGiftCard);
userRouter.get("/getAllGiftCard/:email", userController.getAllGiftCards);
userRouter.get("/leaderboard/:coin", userController.getLeaderboard);
userRouter.get("/transactions-report/:email", userController.getTransactionReport);
userRouter.post("/validate-sell", userController.validateTokenSell);
userRouter.post("/addpersonalinfo", userController.addPersonalInfo);
userRouter.post("/ambassadors", userController.applyForAmbassador);
userRouter.get("/ambassadors", userController.getAmbassadors);

// Linked mining accounts
userRouter.get("/linked-accounts", validateAuthHeader, userController.getLinkedAccounts);
userRouter.post("/linked-accounts/request", validateAuthHeader, userController.requestLinkedAccount);
userRouter.post("/linked-accounts/verify", validateAuthHeader, userController.verifyLinkedAccount);
userRouter.delete("/linked-accounts/:linkId", validateAuthHeader, userController.removeLinkedAccount);
// userRouter.post("/updatePassword", userController.updatePassword);
// userRouter.post("/updateEmail", userController.updateEmail);
// userRouter.post("/updatePhone", userController.updatePhone);
// userRouter.post("/updateAddress", userController.updateAddress);
// userRouter.post("/updatePayment", userController.updatePayment);
// userRouter.post("/updateWallet", userController.updateWallet);
// userRouter.post("/updateReferral", userController.updateReferral);
// userRouter.post("/updateReferrer", userController.updateReferrer);
// userRouter.post("/updateReferralCode", userController.updateReferralCode);
// userRouter.post("/updateReferrerCode", userController.updateReferrerCode);
// userRouter.post("/updateReferralStatus", userController.updateReferralStatus);
// userRouter.post("/updateReferrerStatus", userController.updateReferrerStatus);
// userRouter.post("/updateReferralCodeStatus", userController.updateReferralCodeStatus);
// userRouter.post("/updateReferrerCodeStatus", userController.updateReferrerCodeStatus);
// userRouter.post("/updateReferralRewards", userController.updateReferralRewards);
// userRouter.post("/updateReferrerRewards", userController.updateReferrerRewards);
// userRouter.post("/updateReferralCodeRewards", userController.updateReferralCodeRewards);
// userRouter.post("/updateReferrerCodeRewards", userController.updateReferrerCodeRewards);
// userRouter.post("/updateReferralRewardsStatus", userController.updateReferralRewardsStatus);
// userRouter.post("/updateReferrerRewardsStatus", userController.updateReferrerRewardsStatus);
// userRouter.post("/updateReferralCodeRewardsStatus", userController.updateReferralCodeRewardsStatus);
// userRouter.post("/updateReferrerCodeRewardsStatus", userController.updateReferrerCodeRewardsStatus);
// userRouter.post("/updateReferralRewardsAmount", userController.updateReferralRewardsAmount);
// userRouter.post("/updateReferrerRewardsAmount", userController.updateReferrerRewardsAmount);
// userRouter.post("/updateReferralCodeRewardsAmount", userController.updateReferralCodeRewardsAmount);
// userRouter.post("/updateReferrerCodeRewardsAmount", userController.updateReferrerCodeRewardsAmount);
// userRouter.post("/updateReferralRewardsDate", userController.updateReferralRewardsDate);

// Phone registration and authentication
userRouter.post("/registerWithPhone", userController.registerUserWithPhone);
userRouter.post("/sendPhoneOtp", userController.sendOtpToPhone);
userRouter.post("/validatePhoneOtp", userController.validatePhoneOtp);
userRouter.post("/loginWithPhone", validateWhitelistOnLogin, userController.loginWithPhone);
userRouter.post("/fallbackToEmailLogin", validateWhitelistOnLogin, userController.fallbackToEmailLogin);
userRouter.post("/saveDeviceToken", userController.updateFirebaseToken);

export const authRoutes = userRouter;
